base/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views, user_login
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('base', views.base),
    path('', views.index,name='index'),
    path('about.html', views.about,name='about'),
    path('internships.html', views.internships,name='internships'),  
    path('accounts/', include('django.contrib.auth.urls')), 
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('doLogin', user_login.DO_LOGIN,name='doLogin'),
    path('home.html',views.home,name='home'),
    path('profile.html',views.PROFILE,name='profile'),
    path('profile.html/update',views.PROFILE_UPDATE,name="profile_update"),
    path('logout/', views.logout_view, name='logout'),
    path('contacts.html', views.contact_view, name='contact'),
    path('index.html', views.contact_index, name='contacts'),
    path('enrolledinternship.html', views.enrolledinternship,name='enrolledinternship'),
    path('<slug:slug>',views.INTERNSHIPS_DETAILS,name='internships_details'),
    path('enrolled-internships/', views.enrolledinternship, name='enrolled_internships'),
    path('<slug:slug>/', views.ENROLLEDCOURSE_DETAILS, name='enrolledcourse_details'),


] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

internsveda/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),

]

base/models.py
from typing import Any
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.urls import reverse

class Contact_us(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=255)
    category = models.CharField(max_length=50, default='Categories')
    message = models.TextField()

    def __str__(self):
        return self.email
    
class Categories(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    def get_all_category(self):
        return Categories.objects.all().order_by('id')

class Author(models.Model):
    author_profile = models.ImageField(upload_to="Media/author")
    name = models.CharField(max_length=100, null=True)
    about_author = models.TextField()

    def __str__(self):
        return self.name
    


class Internships(models.Model):
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),
    )

    featured_image = models.ImageField(upload_to="Media/featured_img",null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    modules = models.IntegerField(default=0)
    author = models.ForeignKey(Author,on_delete=models.CASCADE,null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    description = models.TextField()
    price = models.IntegerField(null=True,default=0)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)


    def __str__(self):
        return self.title
       
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("internships_details", kwargs={'slug': self.slug})

    def get_url_ec(self):
        from django.urls import reverse
        return reverse("enrolledcourse_details", kwargs={'slug': self.slug})
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Internships.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Internships)

class LEARNING_OUTCOMES(models.Model):
    course = models.ForeignKey(Internships, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points
    
class UserInternship(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    internships = models.ForeignKey(Internships,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name+" - "+self.internships.title
    

class Lesson(models.Model):
    Internships = models.ForeignKey(Internships,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name + " - " + self.Internships.title
class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    internships = models.ForeignKey(Internships, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    video_file = models.FileField(upload_to='videos/')  # Define a FileField for uploading video files

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("video_detail", kwargs={"pk": self.pk})

base/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout
from .models import *
from django.shortcuts import render, get_object_or_404  

# Create your views here.
def base (request):
    return render(request,'base.html')
def index (request):
    return render(request,'main/index.html')
def about (request):
    return render(request,'about.html')
def internships (request):
    category = Categories.objects.all().order_by('id')
    internships = Internships.objects.filter(status = 'PUBLISH').order_by('id')
    context = {
        'category':category,
        'internships' : internships,     
    }
    return render(request,'internships.html',context)

def enrolledinternship(request):
    user_internships = UserInternship.objects.filter(user=request.user).select_related('internships')
    internships = [ui.internships for ui in user_internships]
    
    context = {
        'internships': internships,
    }
    return render(request, 'enrolledinternship.html', context)
def home (request):
    return render(request,'main/home.html')
def DO_LOGIN (request):
    return render(request,'login.html')
def SINGLE_INTERNSHIP(request):
    return render(request,'single_internship.html')
def PROFILE(request):
    return render(request,'registration/profile.html')
def PROFILE_UPDATE(request):
    if request.method == "POST":
      username = request.POST.get('username')
      first_name = request.POST.get('first_name')
      last_name = request.POST.get('last_name')
      email = request.POST.get('email')
      password = request.POST.get('password')
      user_id = request.user.id

      user = User.objects.get(id=user_id)
      user.first_name = first_name
      user.last_name = last_name
      user.username = username
      user.email = email

      if password != None and password != "":
       user.set_password(password)
      
      user.save()
      messages.success(request,'Profile Is Successfully Updated.')
      return redirect('profile') 
def logout_view(request):
    logout(request)
    return redirect('login')

def contact_view(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        contact = Contact_us(
            name=name,
            email=email,
            subject=subject,
            message=message,
        )
        contact.save()
    messages.success(request,'Your Message Is Successfully Delivered.')
    return render(request, 'contacts.html')
def contact_index(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        category = request.POST.get('category')
        subject = request.POST.get('subject')

        contacts = Contact_us(
            name=name,
            email=email,
            category=category,
            subject=subject,
        )
        contacts.save()
    messages.success(request,'Your Message Is Successfully Delivered.')
    return render(request, 'main/index.html')
def SINGLE_INTERNSHIP(request):
    category = Categories.get_all_category(Categories).order_by('id')
    internships = Internships.objects.all
    context = {
        'internships':internships,
        'category':category
    }
    return render(request, 'single_internship.html',context)
def INTERNSHIPS_DETAILS(request, slug):
    category = Categories.objects.all().order_by('id')
    internships = get_object_or_404(Internships, slug=slug)
    learning_outcomes = LEARNING_OUTCOMES.objects.filter(course=internships)

    context = {
        'internships': internships,
        'category': category,
        'learning_outcomes': learning_outcomes
    }
    return render(request, 'single_internship.html', context)
def ENROLLEDCOURSE_DETAILS(request, slug):
    category = Categories.get_all_category(Categories).order_by('id')
    internships = get_object_or_404(Internships, slug=slug)
    learning_outcomes = LEARNING_OUTCOMES.objects.filter(course=internships)
    lesson = Lesson.objects.filter(Internships=internships)

    lesson_videos = {}
    for lesson in lesson:
        lesson_videos[lesson] = lesson.video_set.all()
    
    context = {
        'internships': internships,
        'category': category,
        'learning_outcomes': learning_outcomes,
        'lesson': lesson,
        'lesson_videos': lesson_videos,
    }
    return render(request, 'enrolledcourse.html', context)

base/templates/base.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
  {% load static %}
  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Favicon -->
  <link rel="shortcut icon" href="img/fav.png" />
  <!-- Author Meta -->
  <meta name="author" content="colorlib" />
  <!-- Meta Description -->
  <meta name="description" content="" />
  <!-- Meta Keyword -->
  <meta name="keywords" content="" />
  <!-- meta character set -->
  <meta charset="UTF-8" />
  <!-- Site Title -->
  <title>Internsveda</title>

  <link href="https://fonts.googleapis.com/css?family=Playfair+Display:900|Roboto:400,400i,500,700" rel="stylesheet" />
  <!--
      CSS
      =============================================
    -->
  <link rel="stylesheet" href="{% static 'css/linearicons.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
  {% include 'components/header.html' %}
  {%block content%}
  {% endblock %} 
  <a href="https://wa.me/+918847010952?text=I'm%20interested%20in%20to%chat" style="position:fixed; bottom:05% !important; right: 03% !important;">
    <img src="{% static 'img/whatsapp.png'%}" alt="" width="60px"  style="border-radius: 18px;">
  </a>
  {% include 'components/footer.html'%}
  <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
  <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>   
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/filter.js'%}"></script>
 </body>
</html>

base/templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ================ start banner Area ================= -->
<section class="banner-area">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-12 banner-right">
                <h1 class="text-white">
                    Contacts
                </h1>
                <br>
                <div class="link-nav">
                    <span class="box">
                        <a href="{% url 'index' %}">Home </a>
                        <i class="lnr lnr-arrow-right"></i>
                        <a href="contacts.html">Contacts</a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ================ End banner Area ================= -->

<!-- ================ Start contact-page Area  ================= -->
<h1 style="text-align:center;">Send us a Message</h1><br>
<p style="text-align:center;">Send us an email with your details and we will get back to you in some time.</p>
<section class="contact-page-area section-gap" style="display: flex; justify-content: center; align-items: center; padding: 20px;">
    <div class="col-lg-8" style="max-width: 100%; width: 100%; box-sizing: border-box;">
        <form class="form-area contact-form text-right" action="contacts.html" id="myForm" method="post" style="display: flex; flex-direction: column; align-items: center; width: 100%;">
            {% csrf_token %}
			{{ form.as_p }}
            <div class="row" style="width: 100%; display: flex; flex-wrap: wrap; justify-content: center;">
                <div class="col-lg-6 form-group" style="padding: 10px; box-sizing: border-box; flex: 1 1 100%; max-width: 100%;">
                    <h3 style="text-align: left; width: 100%;">Personal Information</h3><br>
                    <input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'"
                        class="common-input mb-20 form-control" required="" type="text" style="width: 100%; margin-bottom: 10px;">

                    <input name="email" placeholder="Enter email address" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control"
                        required="" type="email" style="width: 100%; margin-bottom: 10px;">

                    <input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter subject'"
                        class="common-input mb-20 form-control" required="" type="text" style="width: 100%; margin-bottom: -10px;">
                </div>
                <div class="col-lg-6 form-group" style="padding: 10px; box-sizing: border-box; flex: 1 1 100%; max-width: 100%;">
                    <h3 style="text-align: left; width: 100%;">Write Your Message</h3><br>
                    <textarea class="common-textarea form-control" name="message" placeholder="Enter Message" onfocus="this.placeholder = ''"
                        onblur="this.placeholder = 'Enter Message'" required="" style="width: 100%; height: 150px; margin-bottom: 0px;"></textarea>
                </div>
                <div class="col-lg-12" style="padding: 10px; box-sizing: border-box; text-align: center;">
                    <div class="alert-msg" style="text-align: left; width: 100%;"></div>
                    <button class="btn" style="float: none; margin-bottom: 12px; width:200px; height:50px; color:#fff;">Send Message</button>
                </div>
            </div>
        </form>
    </div>
</section>
<!-- ================ End contact-page Area ================= -->
{% endblock %}

base/templates/enrolledcourse.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
  {% load static %}
  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Favicon -->
  <link rel="shortcut icon" href="img/fav.png" />
  <!-- Author Meta -->
  <meta name="author" content="colorlib" />
  <!-- Meta Description -->
  <meta name="description" content="" />
  <!-- Meta Keyword -->
  <meta name="keywords" content="" />
  <!-- meta character set -->
  <meta charset="UTF-8" />
  <!-- Site Title -->
  <title>Internsveda</title>

  <link href="https://fonts.googleapis.com/css?family=Playfair+Display:900|Roboto:400,400i,500,700" rel="stylesheet" />
  <!--
      CSS
      =============================================
    -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  <link rel="stylesheet" href="{% static 'css/linearicons.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>  
<header class="default-header">
    <nav class="navbar navbar-expand-lg  navbar-light">
      <div class="container">
        <a class="navbar-brand" href="index.html">
          <img style="height:60px; width:70px; margin-right:-20px" src="{%static 'img/sitelogo.png'%}" alt="" />
        </a>
        <h2 style="color:#E8762E">Internsveda</h2>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="lnr lnr-menu"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li><a href="{% url 'home'%}">Home</a></li>
            <li><a href="{% url 'enrolledinternship' %}">Enrolled Internships</a></li>
          <!--  <li><a href="courses.html">Placements</a></li> -->
            <li><a href="{% url 'profile'%}">My, Account</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <!-- ================ End Header Area ================= -->
  <style>
    .box-internships-img img{
      height:340px; 
      width:600px;
    }
    .Certification {
        display: flex;
        justify-content: space-around; 
        align-items: center;
        margin-top: 30px; 
    }
    
    .Certification img {
        height: 50vh;
        width: auto; 
        display: block; 
        margin: 0 10px; 
        margin-top: 20px;
        border: 1px solid #ccc; 
        border-radius: 5px; 
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); 
    }
    
    /* Mobile view */
    @media (max-width: 780px) {
      .box-internships-img{
        align-items: center;
      }
      .box-internships-img img{
        height:280px; 
        width:380px;
      }
        .Certification {
            flex-direction: column;
            width: 100%;
        }
    
        .Certification img {
            height: 40vh;
            width: 100%; /* Ensure the image fills the container width */
            margin: 10px 0;
        }
    }
    

    .course-curriculum {
      max-width: 800px;
      margin: 0 auto;
      padding: 30px;
    }
    
    .course-curriculum h2 {
      text-align: center;
      margin-bottom: 20px;
    }
    
    .course-curriculum ul {
      list-style-type: none;
      padding: 0;
    }
    
    .module {
      margin-bottom: 20px;
    }
    
    .module-title {
      font-size: 26px;
      cursor: pointer;
      color: #007bff; 
    }
    
    .topics {
      display: none;
    }
    
    .module.open .topics {
      display: block;
    }
    /* Modal styles */
    .modal-trigger {
      display: none;
    }
    
    .modal {
      display: none;
      position: fixed;
      z-index: 1000; /* Adjust the z-index as needed */
      left: 0;
      top: 0;
      width: 100%;
      height: 100%;
      overflow: auto;
      background-color: rgba(0, 0, 0, 0.8);
    }
    
    .modal-trigger:checked + .modal {
      display: flex;
      align-items: center;
      justify-content: center;
    }
    
    .modal-content {
      width: 80%;
      max-width: 800px;
    }
    
    .modal video {
      width: 100%;
      height: auto;
    }
    
    .modal .close {
      position: absolute;
      top: 15px;
      right: 15px;
      color: white;
      font-size: 30px;
      cursor: pointer;
    }
    
    /* Only allow subsequent videos to be played if the previous one has been watched */
    .modal-trigger:not(:checked) + .modal {
      pointer-events: none;
    }

.video-info {
  display: flex;
  align-items: center;
}

/* Style the play button label */
.play-video {
  cursor: pointer;
  margin-left: auto; 

}

/* Style the play icon */
.play-video i {
  font-size: 16px; 
}

  </style>
    
    <!-- ================ start banner Area ================= -->
      <section class="banner-area">
          <div class="container">
            <div class="row justify-content-center align-items-center">
              <div class="col-lg-12 banner-right">
                 <h2 style="color:#fff">{{ internships.title }}</h2>
                <br>
                <div class="link-nav">
                  <span class="box">
                    <a href="{% url 'index' %}">Home</a>
                    <i class="lnr lnr-arrow-right"></i>
                    <a href=""></a>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </section>
      <!-- ================ End banner Area ================= -->
    
      <!-- ================ Start Feature Area ================= -->
      <section class="feature-area" style="margin-bottom:16px;">
        <div class="container-fluid">
          <div class="feature-inner row">
            <div class="col-lg-2 col-md-6">
              <div class="feature-item d-flex">
                <i class="ti-book"></i>
                <div class="ml-20">
                  <h4>New Classes</h4>
                  <p>
                    In the history of modern astronomy, there is probably no one greater leap forward.
                  </p>
                </div>
              </div>
            </div>
            <div class="col-lg-2 col-md-6">
              <div class="feature-item d-flex">
                <i class="ti-cup"></i>
                <div class="ml-20">
                  <h4>Top Courses</h4>
                  <p>
                    In the history of modern astronomy, there is probably no one greater leap forward.
                  </p>
                </div>
              </div>
            </div>
            <div class="col-lg-2 col-md-6">
              <div class="feature-item d-flex border-right-0">
                <i class="ti-desktop"></i>
                <div class="ml-20">
                  <h4>Full E-Books</h4>
                  <p>
                    In the history of modern astronomy, there is probably no one greater leap forward.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- ================ End Feature Area ================= -->
    
      
    
     <!--================ Start Course Details Area =================-->
     <section class="course-details-area">
      <div class="container">
              <h1 style="margin-bottom:40px; text-align:center">{{internships.title}}</h1> 
              <span class="mb-1 d-inline-block text-gray-600">{{internships.category.name}}</span>
              <div class="row">
              <div class="col-lg-8 course-details-left">
                  <div class="main-image">
                    <div class="box-internships-img">
                      <img src="{{ internships.featured_image.url }}" alt="">
                    </div>
                  
                    <div class="content-wrapper" style="margin-top:20px;">
                      <h2 class="title">Objectives</h2>
                      <div class="content" style="margin-top:20px;">
                        {{ internships.description }}
                      </div> 
                  </div>
  
                       <h3 class="title" style="margin-top:20px;">Learning Outcome's</h3>
                        <div class="content" style="margin-top:20px;">
                          <ol class="course-list">
                            {% for outcome in learning_outcomes %}
                        <li class="justify-content-between d-flex">{{ outcome.points }}</li>
                             {% endfor %}
                        </ol>
                        </div>
                  </div>
              </div>
  
  
              <div class="col-lg-4 right-contents">
                  <ul>
                      <li class="justify-content-between d-flex">
                              <p>Trainer’s Name</p>
                              <span class="or"> {{ internships.author }}</span>
                      </li>
                      <li class="justify-content-between d-flex">
                        <p>Internships Module's</p>
                        <span class="or"> {{ internships.modules }}</span>
                      </li>
                  </ul>
                    <hr style="border-top: 1px solid;">
                  <h3 class="title" style="margin-top:20px; margin-bottom:10px">Curriculam</h3>
                  {% for lesson in internships.lesson_set.all %}
                  <ul class="curriculum-list" style="font-size:20px; margin-bottom:10px;">
                      <li>
                          <details>
                              <summary style="margin-bottom:10px;">{{ lesson.name }}</summary>
                              <ul class="hidden">
                                  {% for video in lesson.video_set.all %}
                                      <li style="margin-bottom:6px;">
                                          <div class="video-info">
                                              <p style="padding-top:6px">{{ video.title }}</p>
                                              <label for="video{{ video.pk }}" class="play-video">
                                                  <i class="fas fa-play"></i> <!-- Font Awesome play icon -->
                                              </label>
                                          </div>
                                          <input type="checkbox" id="video{{ video.pk }}" class="modal-trigger">
                                          <!-- Modal container -->
                                          <div class="modal">
                                              <label for="video{{ video.pk }}" class="close">&times;</label>
                                              <div class="modal-content">
                                                  <video id="modal-video{{ video.pk }}" width="100%" height="100%" controls controlsList="nodownload">
                                                      <source src="{{ video.video_file.url }}" type="video/mp4">
                                                      Your browser does not support the video tag.
                                                  </video>
                                              </div>
                                          </div>
                                      </li>
                                  {% endfor %}
                              </ul>
                          </details>
                      </li>
                  </ul>
              {% endfor %}
              
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!--================ End Course Details Area =================-->  <br>
    <br>
  <br>

    <a href="https://wa.me/+918847010952?text=I'm%20interested%20in%20to%chat" style="position:fixed; bottom:05% !important; right: 03% !important;">
      <img src="{% static 'img/whatsapp.png'%}" alt="" width="60px"  style="border-radius: 18px;">
    </a>
   <!-- ================ start footer Area ================= -->
   <footer class="footer-area section-gap">
    <div class="footer-bottom row align-items-center">
        <p class="footer-text m-0 col-lg-8 col-md-12" style="padding-left:3%; padding-top:1.2%; padding-bottom:1.2%">
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This website is build by Apoorva Chaddha</p>
        <div class="col-lg-4 col-md-12 footer-social">
          <a href="https://www.linkedin.com/company/internsveda/"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </div>
    </div>
  </div>
  </footer>
  <!-- ================ End footer Area ================= -->
  <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
  <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>   
  <script src="{% static 'js/main.js' %}"></script>
  </body>
  </html>